default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails_ember_starter_development

test:
  <<: *default
  database: rails_ember_starter_test

production:
  <<: *default
  database: rails_ember_starter_production
  username: rails_ember_starter
  password: <%= ENV['RAILS_EMBER_STARTER_DATABASE_PASSWORD'] %>
